export interface StandupEntry {
  id: string;
  name: string;
  date: string; // ISO date string (YYYY-MM-DD)
  yesterday: string;
  today: string;
  blockers: string;
}

// Type for creating new entries (id is generated by storage)
export type NewStandupEntry = Omit<StandupEntry, 'id'>;
