export interface StandupEntry {
  id: string;
  name: string;
  date: string; // ISO date string (YYYY-MM-DD)
  yesterday: string;
  today: string;
  blockers: string;
}

// Type for creating new entries (id is generated by storage)
export type NewStandupEntry = Omit<StandupEntry, 'id'>;

// Storage operation result types
export type StorageErrorType = 'QUOTA_EXCEEDED' | 'PARSE_ERROR' | 'UNKNOWN';

export interface StorageError {
  type: StorageErrorType;
  message: string;
}

export interface StorageResult<T> {
  success: boolean;
  data?: T;
  error?: StorageError;
}
